// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlp8-wzKDP7jkKy3R_5u22_cRzfF0rVzQ',
    appId: '1:713202344389:web:c79846562ace223c1e6bac',
    messagingSenderId: '713202344389',
    projectId: 'flutterappuceva',
    authDomain: 'flutterappuceva.firebaseapp.com',
    storageBucket: 'flutterappuceva.firebasestorage.app',
    measurementId: 'G-R8SKYKPJPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3OOlyGn9bhhDH0DD0N-py2jAY9XQ5O9E',
    appId: '1:713202344389:android:8839d94cb03e32161e6bac',
    messagingSenderId: '713202344389',
    projectId: 'flutterappuceva',
    storageBucket: 'flutterappuceva.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpoGH4H5J7Xq4MVJv2hWm_o-biShl6Eq0',
    appId: '1:713202344389:ios:9abfb8c5176656411e6bac',
    messagingSenderId: '713202344389',
    projectId: 'flutterappuceva',
    storageBucket: 'flutterappuceva.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpoGH4H5J7Xq4MVJv2hWm_o-biShl6Eq0',
    appId: '1:713202344389:ios:9abfb8c5176656411e6bac',
    messagingSenderId: '713202344389',
    projectId: 'flutterappuceva',
    storageBucket: 'flutterappuceva.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlp8-wzKDP7jkKy3R_5u22_cRzfF0rVzQ',
    appId: '1:713202344389:web:02c0b019f886218c1e6bac',
    messagingSenderId: '713202344389',
    projectId: 'flutterappuceva',
    authDomain: 'flutterappuceva.firebaseapp.com',
    storageBucket: 'flutterappuceva.firebasestorage.app',
    measurementId: 'G-10FNH92WRH',
  );
}
